---  
spring: 
  datasource: 
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/atcrowdfunding180808
    username: root
    password: 9527
    driver-class-name: com.mysql.jdbc.Driver
mybatis:   
  mapperLocations: classpath*:mybatis/*Mapper.xml
  typeAliasesPackage: com.atguigu.atcrowdfunding.bean
